//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_EXPENSE_ITEM
    {
        public long EXP_ITEM_ID { get; set; }
        public string EXP_FORM_ID { get; set; }
        public string FIN_SUBJECT_ID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string ITEM_REMARK { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string ITEM_UNIT { get; set; }
        public Nullable<decimal> ITEM_UNIT_PRICE { get; set; }
        public Nullable<decimal> ITEM_QUANTITY { get; set; }
    }
}
