//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_EXPENSE_FORM
    {
        public string EXP_FORM_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public Nullable<int> OCCURRED_YEAR { get; set; }
        public Nullable<int> OCCURRED_MONTH { get; set; }
        public Nullable<System.DateTime> PAYMENT_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string REMARK { get; set; }
        public string PASS_CREATE_ID { get; set; }
        public Nullable<System.DateTime> PASS_CREATE_DATE { get; set; }
        public string APPROVE_CREATE_ID { get; set; }
        public Nullable<System.DateTime> APPROVE_CREATE_DATE { get; set; }
        public string JOURNAL_CREATE_ID { get; set; }
        public Nullable<System.DateTime> JOURNAL_CREATE_DATE { get; set; }
        public string REJECT_DESC { get; set; }
        public string PAYEE { get; set; }
    }
}
