//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_VALUATION_FORM
    {
        public string VA_FORM_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public Nullable<decimal> VALUATION_AMOUNT { get; set; }
        public Nullable<decimal> TAX_RATIO { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<decimal> RETENTION_PAYMENT { get; set; }
        public Nullable<decimal> ADVANCE_PAYMENT { get; set; }
        public Nullable<decimal> ADVANCE_PAYMENT_REFUND { get; set; }
        public Nullable<decimal> OTHER_PAYMENT { get; set; }
        public string OTHER_PAYMENT_REMARK { get; set; }
        public Nullable<decimal> REPAYMENT { get; set; }
        public string REMARK { get; set; }
        public string CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
