//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_ESTIMATION_INVOICE
    {
        public long INVOICE_ID { get; set; }
        public string EST_FORM_ID { get; set; }
        public string CONTRACT_ID { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public string TYPE { get; set; }
        public string NOTE { get; set; }
        public string SUB_TYPE { get; set; }
        public string PLAN_ITEM_ID { get; set; }
        public Nullable<decimal> DISCOUNT_QTY { get; set; }
        public Nullable<decimal> DISCOUNT_UNIT_PRICE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
