//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_COSTCHANGE_FORM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLAN_COSTCHANGE_FORM()
        {
            this.PLAN_COSTCHANGE_ITEM = new HashSet<PLAN_COSTCHANGE_ITEM>();
        }
    
        public string FORM_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public string REMARK_ITEM { get; set; }
        public string REMARK_QTY { get; set; }
        public string REMARK_PRICE { get; set; }
        public string REMARK_OTHER { get; set; }
        public string REASON_CODE { get; set; }
        public string METHOD_CODE { get; set; }
        public Nullable<System.DateTime> SETTLEMENT_DATE { get; set; }
        public string REJECT_DESC { get; set; }
        public string MODIFY_USER_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string STATUS { get; set; }
        public string INQUIRY_FORM_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAN_COSTCHANGE_ITEM> PLAN_COSTCHANGE_ITEM { get; set; }
    }
}
