//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_FUNCTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_FUNCTION()
        {
            this.SYS_PRIVILEGE = new HashSet<SYS_PRIVILEGE>();
        }
    
        public string FUNCTION_ID { get; set; }
        public string FUNCTION_NAME { get; set; }
        public string MODULE_NAME { get; set; }
        public string SUB_MODULE { get; set; }
        public string FUNCTION_URI { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_ID { get; set; }
        public string ISMENU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_PRIVILEGE> SYS_PRIVILEGE { get; set; }
    }
}
