//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER
    {
        public string USER_ID { get; set; }
        public string ROLE_ID { get; set; }
        public string USER_NAME { get; set; }
        public string EMAIL { get; set; }
        public string TEL { get; set; }
        public string TEL_EXT { get; set; }
        public string PASSWORD { get; set; }
        public string FAX { get; set; }
        public string MOBILE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_ID { get; set; }
        public string DEP_CODE { get; set; }
    
        public virtual SYS_ROLE SYS_ROLE { get; set; }
    }
}
