//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MESSAGE
    {
        public long MSG_ID { get; set; }
        public string FROM_ADDRESS { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string MAIL_LIST { get; set; }
        public string BCC_MAIL_LIST { get; set; }
        public string SUBJECT { get; set; }
        public string MSG_BODY { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<System.DateTime> SEND_TIME { get; set; }
        public string CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string STATUS { get; set; }
    }
}
