//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PRIVILEGE
    {
        public string PRIVILEGE_ID { get; set; }
        public string ROLE_ID { get; set; }
        public string FUNCTION_ID { get; set; }
        public string ACTION_1_RIGHT { get; set; }
        public string ACTION_1_NAME { get; set; }
    
        public virtual SYS_FUNCTION SYS_FUNCTION { get; set; }
        public virtual SYS_ROLE SYS_ROLE { get; set; }
    }
}
