//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TND_PROJECT_ITEM
    {
        public string PROJECT_ITEM_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public string ITEM_ID { get; set; }
        public string ITEM_DESC { get; set; }
        public string ITEM_UNIT { get; set; }
        public Nullable<decimal> ITEM_QUANTITY { get; set; }
        public Nullable<decimal> ITEM_UNIT_PRICE { get; set; }
        public Nullable<decimal> MAN_PRICE { get; set; }
        public string ITEM_REMARK { get; set; }
        public string TYPE_CODE_1 { get; set; }
        public string TYPE_CODE_2 { get; set; }
        public string SUB_TYPE_CODE { get; set; }
        public string SYSTEM_MAIN { get; set; }
        public string SYSTEM_SUB { get; set; }
        public string MODIFY_USER_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string SHEET_NAME { get; set; }
        public Nullable<long> EXCEL_ROW_ID { get; set; }
        public Nullable<decimal> QUO_PRICE { get; set; }
        public string DEL_FLAG { get; set; }
    }
}
