//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TND_PROJECT_FORM
    {
        public string FORM_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public string FORM_NAME { get; set; }
        public string OWNER_NAME { get; set; }
        public string OWNER_TEL { get; set; }
        public string OWNER_EMAIL { get; set; }
        public string OWNER_FAX { get; set; }
        public string SUPPLIER_ID { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public string REF_ID { get; set; }
        public string CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string MODIFY_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string STATUS { get; set; }
        public string ISWAGE { get; set; }
    }
}
