//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TND_SUP_CONTACT_INFO
    {
        public long CONTACT_ID { get; set; }
        public string SUPPLIER_MATERIAL_ID { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_TEL { get; set; }
        public string CONTACT_FAX { get; set; }
        public string CONTACT_MOBIL { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string REMARK { get; set; }
    }
}
