//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace topmeperp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TND_SUPPLIER
    {
        public string SUPPLIER_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_ID { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string COMPANY_TEL { get; set; }
        public string COMPANY_FAX { get; set; }
        public string CONTACT_MOBILE { get; set; }
        public string SUPPLY_NOTE { get; set; }
        public string REGISTER_ADDRESS { get; set; }
        public string CONTACT_ADDRESS { get; set; }
        public string TYPE_MAIN { get; set; }
        public Nullable<int> TYPE_SUB { get; set; }
    }
}
